stages:
  - release

helm_release:
  stage: release
  image: kanomnutt/helm:latest
  before_script:
  - LAST_COMMIT=$(git rev-parse HEAD^1)
  - CHANGED_FILE=$(git diff --name-only $LAST_COMMIT | grep charts)
  - FOLDER_PATH=$(dirname $CHANGED_FILE | head -n 1)
  - HELM_PROJECT=$(basename $FOLDER_PATH | cut -d '/' -f2)
  - echo $LAST_COMMIT && echo $CHANGED_FILE && echo $FOLDER_PATH && echo $HELM_PROJECT
  - helm repo add --username $CI_REGISTRY_USERNAME --password $CI_REGISTRY_PASSWORD $HELM_PROJECT $CI_REGISTRY_URL
  - helm plugin install https://github.com/chartmuseum/helm-push
  script:
    - cd $FOLDER_PATH
    - helm package .
    - helm cm-push . $HELM_PROJECT
  rules:
    - if: '$CI_COMMIT_TAG'
      changes: 
      - charts/**/*