{{- if .Values.PodDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.serviceName }}-pdb
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
    {{- toYaml .Values.Labels | nindent 4 }}
spec:
  selector:
    matchLabels:
        {{- toYaml .Values.Labels | nindent 6 }}
  minAvailable: {{ .Values.PodDisruptionBudget.minAvailable }}
  maxUnavailable: {{ .Values.PodDisruptionBudget.maxUnavailable }}
{{- end }}