apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}-service
  labels:
    {{- toYaml .Values.Labels | nindent 4 }}
    {{- include "deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: {{ .Values.serviceName }}
  selector:
    {{- toYaml .Values.Labels | nindent 4 }}
